### ISSUE TITLE
Feature request: If there's no package found when I add a package, suggest closest neighbor. 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/Pkg.jl#1252] opened 2019-07-14 20:42 UTC
In Julia, if I have a function defined and I call it with the incorrect signature, I get an error and suggestion as to the closest candidates. 

In the package manager, however, if I type `] add test` and `test` does not exist but `Test` does exist, I get an error, and no indication as to what the issue was besides that `test` does not exist. 

It would be very helpful for Pkg.jl to give me the closest candidate suggestion.  I see case-specific errors all of the time on slack where someone gets the package not found an error, wastes their time trying to figure it out, and then goes on slack to ask, only for it to be an issue with the wrong capitalization.

**Comment by fredrikekre** [comment] 2019-07-14 21:00
Duplicate of #616

**Closed by fredrikekre** 2019-07-14 21:00 UTC
