### ISSUE TITLE
Feature request: `Pkg.generate(".")` should use the current folder name to generate a new environment in the current folder

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/Pkg.jl#3025] opened 2022-03-09 17:44 UTC
Currently, the following does not appear to work:

```
$ mkdir EarthquakeAnalysisEnv && cd EarthquakeAnalysisEnv
$ julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.59 (2022-02-22)
 _/ |\__'_|_|_|\__'_|  |  Commit 6fa255d0f7 (15 days old master)
|__/                   |

(@v1.9) pkg> generate .
ERROR: "." is not a valid package name
```

It would be nice if `generate .` created a `Project.toml`, `src` etc in the current folder.

Right now, I have to first exit the Julia REPL, then `cd .. && rm EarthquakeAnalysisEnv && julia -e 'using Pkg; Pkg.generate("EarthquakeAnalysisEnv")' && cd EarthquakeAnalysisEnv && julia --project`.

I could attempt to do this from within the REPL but weird stuff happens when I delete the folder that I'm `cd`'d into.

Thoughts?

**Comment by fredrikekre** [comment] 2022-03-09 19:41
Duplicate of  #2821.

**Closed by fredrikekre** 2022-03-09 19:41 UTC

**Comment by kdheepak** [comment] 2022-03-10 03:09
My github issue search completely failed me, thanks for linking the duplicate.
