### ISSUE TITLE
Printing "Resolving packages..." after the build step is confusing

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#1063] opened 2019-02-15 12:46 UTC
Sometimes we run the resolver as part of the build step. The typical output is then something like

```
Building Foo
Resolving packages
<FOO BUILD RUNS HERE>
```

If the build takes a long time it looks like the resolver is really slow while actually it is the build step that is taking time.

**Comment by 00vareladavid** [comment] 2019-02-15 19:33
duplicate of #910

**Closed** 2019-02-15 20:01 UTC
