### ISSUE TITLE
[Feature request] Add shortcut for `activate`

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/Pkg.jl#3563] opened 2023-07-29 17:16 UTC
This is perhaps the most used command in the package manager, it is very long to type...

Can we have a shortcut for it like we do for `status`? I ❤️ `st`

**Comment by IanButterworth** [comment] 2023-07-29 17:26
Duplicate of #3266

**Closed** 2023-07-29 17:26 UTC

**Comment by juliohm** [comment] 2023-07-29 17:51
How is that a duplicate of #3266? Can you clarify @IanButterworth ?

**Comment by juliohm** [comment] 2023-07-29 17:52
You probably meant https://github.com/JuliaLang/Pkg.jl/issues/3256
