### ISSUE TITLE
Feature request: `add MyPackage#fork:branch`

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/Pkg.jl#969] opened 2018-12-20 19:12 UTC
A regular `Pkg` use case for me is to check out a PR branch of some package. Often, the PR branch lives on a different fork. So my current workflow is to first `dev MyPackage`, and then manually add the fork and check out the PR branch. However, for PR branches that live in the source repo, I can just do `add MyPackage#branch`. It'd be great if something like 

```
add MyPackage#fork:branch
```

were possible as well.

**Comment by fredrikekre** [comment] 2018-12-20 19:44
Note that you can always add the fork with url:
```
pkg> add www.fork.com/Package.jl#branch
```

**Comment by tkoolen** [comment] 2018-12-20 21:58
That's a good point. And I guess `add MyPackage#fork:branch` would have to make assumptions regarding where the fork lives. Still, it would be convenient to have with the vast majority of packages (and their forks) living on GitHub.

**Comment by 00vareladavid** [comment] 2018-12-20 22:06
Duplicate of #740

**Closed** 2018-12-20 22:10 UTC
