### ISSUE TITLE
dev doesn't allways get the latest version of a package

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/Pkg.jl#1460] opened 2019-10-21 04:01 UTC
Sometimes `dev https://github.com/someone/SomePackage.jl` gives you an old version of a package from the clones folder without pulling the latest changes. It doesn't error or tell you it has done this. 

The solution is to just delete the `clones` folder and the current `dev/SomePackage` folder and start again, which is very clunky.

**Comment by fredrikekre** [comment] 2019-10-21 15:04
Duplicate of #465

**Closed by fredrikekre** 2019-10-21 15:04 UTC
