### ISSUE TITLE
REPL mode gives different behavior when activating with @

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/Pkg.jl#2983] opened 2022-02-13 19:24 UTC
There is different behavior when activating an environment with "@" as the first character, between REPL mode and functional mode:
```julia
julia> pkg"activate @test"
  Activating new project at `~/.julia/environments/test`

julia> Pkg.activate("@test")
  Activating new project at `~/Documents/@test`
```
~~If this is intended behavior, what is the correct way to activate an env in the Julia depot using Pkg's functional mode?~~
(Nevermind, it's just `shared = true`)

**Comment by mkitti** [comment] 2022-02-13 20:21
I actually think this is a bug. The alternative version is `pkg"activate @test"`, but that is still meant for interactive use.

**Comment by DilumAluthge** [comment] 2022-02-13 20:30
Duplicate of https://github.com/JuliaLang/Pkg.jl/issues/2367?

**Comment by DilumAluthge** [comment] 2022-02-13 20:31
I'm inclined to agree with @fredrikekre's comment here: https://github.com/JuliaLang/Pkg.jl/issues/2367#issuecomment-769447736

**Comment by MilesCranmer** [comment] 2022-02-13 20:34
This does make sense in theory, but it's tripped up a few people now (enough for two GH issues) so it might be good to at least add a warning to `activate("@...` that the user should use `shared` instead.

Also, regarding this:
```julia
Pkg.pkg"activate @global_env"
```
Is there a way to pass an IOStream here? This is the reason I am using the functional API rather than REPL.

**Comment by fredrikekre** [comment] 2022-02-13 20:37
Use the shared argument.

**Closed by fredrikekre** 2022-02-13 20:37 UTC

**Comment by MilesCranmer** [comment] 2022-02-13 20:41
I would just add that it does still feel like unexpected behavior that an identical string passed to the REPL version and the functional version should give entirely different paths, (keeping in mind that "@" is a valid character in filenames). At the very least passing "@" to the functional API should raise an error or warning.

**Comment by mkitti** [comment] 2022-02-13 20:46
> it might be good to at least add a warning to `activate("@...` that the user should use `shared` instead.

I think this is a reasonable consideration. You could suppress the warning with `shared = false` since that would be explicit.

**Comment by DilumAluthge** [comment] 2022-02-13 20:47
#2984

**Comment by MilesCranmer** [comment] 2022-02-13 20:49
Beat me to the PR by 1 minute @DilumAluthge :) Thanks!
