### ISSUE TITLE
Feature request: `]test --quiet` (don't always dump the whole manifest on `Pkg.test()`)

### ISSUE THREAD

**Issue by pbouffard** [JuliaLang/Pkg.jl#3927] opened 2024-06-13 18:48 UTC
I find it annoying that `] test` always dumps the whole manifest before running tests. I'm almost never interested in that info and it's just noise to me most of the time. If I was designing the feature in the first place I would have made this an optional switch (`[--verbose]` or maybe `[-m|--manifest]`) and not include it by default. But probably now people rely on having that output captured. So a switch like `[--quiet]` that suppresses that output would seem like the way to go.

I'll probably contribute the PR for this myself, it's probably a quick one, but I'm opening the issue in case it's already been discussed or is already out there in some existing PR.

**Comment by KristofferC** [comment] 2024-06-14 08:53
The reason it is shown is that package versions during tests are not always the same as what you are running with in normal cases and you also have the extra test-specific dependencies and knowing the version of those is probably also useful. I agree that it is a bit verbose.

**Comment by mgkuhn** [comment] 2024-07-16 17:23
Could the two newer methods for specifying test-specific dependencies listed in #3953 not fix this, by not relying on `] test` specific magic to handle the additional dependencies?

**Comment by felixcremer** [comment] 2024-08-01 08:01
This is a duplicate of #3405.

**Closed** 2024-08-01 13:29 UTC
