### ISSUE TITLE
Race condition in writing manifest_usage.toml?

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Pkg.jl#2633] opened 2021-06-18 02:14 UTC
My manifest_usage.toml looks like it may have had a race condition in appending entries, corrupting the file and preventing `Pkg.gc` from running properly:
```
 [["/home/keno/.julia/environments/v1.1/Manifest.toml"]]
 time = 2020-03-03T15:27:50.063Z
 [["/home/keno/VeronaCompiler/Manifest.toml"]]
 time = 2020-03-03T15:27:50.065Z
 7:50.07Z
```
We should use advisory locking to prevent this from happening.

**Comment by DilumAluthge** [comment] 2021-06-18 02:43
Is the issue here that multiple threads of the same Julia process are writing to the same file? Or are multiple different Julia processes writing to the same file?

**Comment by Keno** [comment] 2021-06-18 02:44
Multiple different julia processes presumably.

**Comment by staticfloat** [comment] 2021-06-18 23:21
We write strings out in one big chunk, here:

https://github.com/JuliaLang/Pkg.jl/blob/1685f44ecc6f152c10341930d916a6cc64e1f1bd/src/Types.jl#L467-L476

Does anyone have a better idea on how to do this?

**Comment by vtjnash** [comment] 2021-06-19 00:11
Duplicate of https://github.com/JuliaLang/Pkg.jl/issues/684? (and others?)

FWIW, "append" does not actually put entries at the end of the file as it is emulated differently than the guarantees provided by posix (https://github.com/JuliaLang/julia/issues/3374)

**Comment by IanButterworth** [comment] 2021-06-19 00:20
As an alternative idea.. instead of writing a single toml, maintain a folder of symlinks to manifests that have been used and `touch` them each time the manifests are used, and remove old ones based on `mtime` on the symlinks? The symlink names could be either a doctored version of the path to remove slashes, or just a hash string of the path

**Comment by KristofferC** [comment] 2021-06-19 11:16
Is it really that hard to write a string to a file atomically? Instead of looking at workarounds, can't we just fix the problem?

**Comment by staticfloat** [comment] 2021-06-19 16:09
> As an alternative idea.. instead of writing a single toml, maintain a folder of symlinks to manifests that have been used and `touch` them each time the manifests are used, and remove old ones based on `mtime` on the symlinks? The symlink names could be either a doctored version of the path to remove slashes, or just a hash string of the path

I do wish we could use symlinks, but we also could jus that’s normal files with hashed file names and the path to the manifest as the content. That being said, I don’t like the idea of having a folder with hundreds of tiny files in it when we could have just one file.

**Comment by IanButterworth** [comment] 2021-06-20 13:38
I believe this is what @vtjnash is suggesting?
```julia
usage_file = joinpath(logdir(), usage_filepath)
timedwait(1, pollint=0.1) do # wait until usage file is read-only, or timeout as failsafe
    !isfile(usage_file) || uperm(usage_file) == 0x04
end
try
    isfile(usage_file) && chmod(usage_file, 0o777)
    open(usage_file, append=true) do io
        write(io, entry) # Append entry to log file in one chunk
    end
finally
    chmod(usage_file, 0o444)
end
```

which seems to work, but breaks previous julia versions given the version-common `_usage.toml` files will be read-only

**Comment by IanButterworth** [comment] 2021-06-20 13:55
A backwards-compatible alternative would be to only use the group bit
```
# wait until usage file group setting is read-only, or timeout
# uses the gperm instead of uperm to maintain backwards compatability with 
# older julia versions that require a writeable file
timedwait(1, pollint=0.1) do
    !isfile(usage_file) || gperm(usage_file) == 0x04
end
try
    isfile(usage_file) && chmod(usage_file, 0o777)
    open(usage_file, append=true) do io
        write(io, entry) # Append entry to log file in one chunk
    end
finally
    chmod(usage_file, 0o747)
end
```

**Comment by StefanKarpinski** [comment] 2021-06-22 10:23
The way we handle this in other parts of Pkg is this sequence:

1. Write to a temp file in the same directory as the destination
2. Move the temp file into place, replacing the original
3. Check that the new file has what we want in it
4. If not, try again

This way the move is atomic. It can still happen that two Julia processes try to do this at the same time, in which case what we just tried to write into the file might be absent when we load it at step 3, which is why we try again.

Currently the manifest usage file is an appendable log but that doesn't work well. Instead we should load the whole file, keep only the latest usage entry for each path, write the whole thing back out (via temp file) and then read it again and check to see that the latest entry for the manifest in question is at least as recent as what we're trying to record it as.

**Comment by StefanKarpinski** [comment] 2021-06-22 10:26
Note: given that design, it would have been better to just maintain the file as a simple table from names to timestamps, rather than in the current table of arrays of tables data structure, but I don't think that's a big deal. We can just maintain it as a table of arrays of tables where each array just happens to have only one entry 🤷🏻‍♂️

**Closed** 2021-07-15 16:05 UTC
Labels: bug
