### ISSUE TITLE
Using "up" in package mode makes the Windows REPL change size

### ISSUE THREAD

**Issue by jebej** [JuliaLang/Pkg.jl#641] opened 2018-08-13 14:26 UTC
Using the `up` command on the default Windows REPL (at least on Windows 7) makes the REPL change size and aspect ratio.

It happens during the "Resolving package versions" phase, and am suspecting it's related to opening the powershell. Other commands do not exhibit the issue.

<img src="https://user-images.githubusercontent.com/11141558/44037775-311dee88-9ee3-11e8-81f0-e8ff0b138de7.png" width="1000">

**Comment by jebej** [comment] 2018-08-13 14:30
possibly related: https://github.com/JuliaLang/julia/issues/28561

**Comment by jebej** [comment] 2018-08-13 14:31
Interestingly, this problem is not exhibited in ConEmu, which uses cmd in the background:
![image](https://user-images.githubusercontent.com/11141558/44038137-0ffc7a84-9ee4-11e8-8fff-bd7c50ceefcd.png)

**Comment by KristofferC** [comment] 2018-08-13 15:16
Reproduces by simply executing:

```
julia> run(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -Command ''`)
```

**Comment by ChristianKurz** [comment] 2018-08-14 08:36
I am running julia 1.0.0 in a powershell-window on windows 10 and cannot reproduce this bug.

**Comment by pfitzseb** [comment] 2018-08-14 09:11
Can't repro this either on Windows 10, neither in `cmd` nor in `powershell`.

**Comment by LukasACH** [comment] 2018-08-23 19:54
Happens to me in `Windows 10 x64 1803 Build 10.0.17134.228` and `Julia Version 1.0.0 (2018-08-08)`

It changes to font of the current window to "Raster Fonts" as well as changing the title to "Windows PowerShell".

I'm able to consistenly reproduce it with both this
```julia
julia> run(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -Command ''`)
```
and this command
```julia
shell> powershell -Command ''
```
but not with `powershell -Command ''` directly in the `cmd` and `powershell` ConHost window.

**Comment by thchr** [comment] 2018-10-12 16:48
Also happens for me when e.g. adding any package via `] add ...` (or just updating, `] up`): this changes REPL fonts to raster fonts, changes font sizes, and changes the window header to Windows PowerShell.
 
This only happens on the first such call in a fresh REPL; after re-adjusting fonts, subsequent calls to e.g. `] add ...` do not change anything. 

This is for `Windows 10 Home x64 1803 Build 17134.345` and `Julia Version 1.0.0 (2018-08-08)`, with the usual cmd-terminal promt (e.g. no ConEmu or anything fancy).

**Comment by KristofferC** [comment] 2018-10-12 16:53
And does it reproduce with

```
julia> run(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -Command ''`)
```

?

**Comment by thchr** [comment] 2018-10-12 16:55
> And does it reproduce with
> 
> ```
> julia> run(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -Command ''`)
> ```
> ?

Yep.

**Comment by thchr** [comment] 2018-10-12 19:19
This is probably related: https://github.com/Microsoft/WSL/issues/2050 (can confirm the report reported there; i.e. simply typing `powershell.exe` within WSL similarly messes up the appearance there). 
Curiously, I don't get the same issue if calling `powershell.exe` directly from a cmd prompt.

I guess this is strictly an upstream issue with Windows Console then.

**Comment by thchr** [comment] 2018-11-13 21:16
If https://github.com/JuliaLang/julia/pull/30014 is merged, could this issue be circumvented by using a Julia-bundled `curl` instead of Powershell's `DownloadFile` to download items on Windows?

**Comment by jebej** [comment] 2018-11-13 21:33
Yes that would "solve" the issue, unless Julia uses the powershell for anything other than downloads.

**Comment by thchr** [comment] 2018-12-09 22:18
This seems to be fixed on Windows version 1809 (but still broken in 1803).

**Comment by KristofferC** [comment] 2019-09-11 07:27
Gonna close this since I don't think there is anything we can do here and it is fixed on newer Windows.

**Closed by KristofferC** 2019-09-11 07:27 UTC
