### ISSUE TITLE
instantiate aborts with assertion error

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/Pkg.jl#2214] opened 2020-11-17 20:05 UTC
Julia version: `13aac259a5d1916aeb2d3f6bd687919e25628ade`
Manifest.toml: https://github.com/JuliaPackaging/Yggdrasil/blob/15038bd02d6ddaac5910753600cb7c9501c831ed/.ci/Manifest.toml

```
.ci) pkg> instantiate
ERROR: AssertionError: sourcepath !== nothing
Stacktrace:
  [1] is_package_downloaded(ctx::Pkg.Types.Context, pkg::Pkg.Types.PackageSpec)
    @ Pkg.Operations ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1745
  [2] #12
    @ ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:118 [inlined]
  [3] _all
    @ ./reduce.jl:923 [inlined]
  [4] #all#691
    @ ./reducedim.jl:886 [inlined]
  [5] all
    @ ./reducedim.jl:886 [inlined]
  [6] is_instantiated(ctx::Pkg.Types.Context)
    @ Pkg.Operations ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:118
  [7] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1292
  [8] instantiate
    @ ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1259 [inlined]
  [9] #instantiate#246
    @ ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1255 [inlined]
 [10] instantiate()
    @ Pkg.API ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1255
 [11] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:405
 [12] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:386
 [13] do_cmd
    @ ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:377 [inlined]
 [14] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode ~/builds/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:550
 [15] #invokelatest#2
    @ ./essentials.jl:707 [inlined]
 [16] invokelatest
    @ ./essentials.jl:706 [inlined]
 [17] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/builds/julia/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
 [18] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/builds/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1125
 [19] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:395
```

**Comment by KristofferC** [comment] 2020-11-18 07:58
Can't repro:

``` 
~/JuliaPkgs/Yggdrasil/.ci master~1
❯ git status
HEAD detached at 15038bd0
nothing to commit, working tree clean

~/JuliaPkgs/Yggdrasil/.ci master~1
❯ ~/julia/julia   --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1489 (2020-11-13)
 _/ |\__'_|_|_|\__'_|  |  Commit 13aac259a5* (4 days old master)
|__/                   |

(.ci) pkg> instantiate
   Installed Hiccup ───────────── v0.2.2
   Installed TranscodingStreams ─ v0.9.5
   Installed JSON2 ────────────── v0.3.2
```

**Comment by maleadt** [comment] 2020-12-18 14:37
I've seen this happen here as well. Not sure how to debug, since I can't easily Revise Pkg code.

**Comment by KristofferC** [comment] 2020-12-18 14:43
> Not sure how to debug, since I can't easily Revise Pkg code.

It is pretty easy. Just follow the instructions at https://github.com/JuliaLang/Pkg.jl#pkg (change uuid and load the new Pkg) and make sure you load Revise before loading Pkg.

**Comment by maleadt** [comment] 2021-01-12 11:01
https://github.com/JuliaLang/Pkg.jl/issues/2097#issuecomment-714316161 is the reason for me (it happened with the TOML package).

**Comment by DilumAluthge** [comment] 2021-05-10 06:27
@vchuravy Did you get this issue when taking a manifest generated by Julia 1.X and then instantiating it with Julia 1.Y?

If that's how you got this issue, we can close this issue as a duplicate of #2513.

**Comment by KristofferC** [comment] 2022-05-04 10:11
I think the error message for this has been improved now. It should say that the manifest version is wrong.

**Closed by KristofferC** 2022-05-04 10:11 UTC
Labels: bug
