### ISSUE TITLE
Pkg REPL build gives error

### ISSUE THREAD

**Issue by PaulXiCao** [JuliaLang/Pkg.jl#1515] opened 2019-11-29 23:51 UTC
If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

I run the Pkg REPL and want to use autocomplete in the build function like so
``` julia
pkg > build("<tab>
```
and it throws the following error
``` julia
(v1.2) pkg> build("┌ Error: Error in the keymap
│   exception =
│    unterminated quote
│    Stacktrace:
│     [1] _completions(::String, ::Bool, ::Int64, ::Int64) at /build/julia/src/julia-1.2.0/usr/share/julia/stdlib/v1.2/Pkg/src/REPL/completions.jl:127
│     [2] completions(::String, ::Int64) at /build/julia/src/julia-1.2.0/usr/share/julia/stdlib/v1.2/Pkg/src/REPL/completions.jl:167
│     [3] complete_line(::Pkg.REPLMode.PkgCompletionProvider, ::REPL.LineEdit.PromptState) at /build/julia/src/julia-1.2.0/usr/share/julia/stdlib/v1.2/Pkg/src/REPLMode.jl:552
│     [4] edit_tab(::REPL.LineEdit.MIState, ::Any, ::Any) at /build/julia/src/julia-1.2.0/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1987
└ @ REPL.LineEdit /build/julia/src/julia-1.2.0/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2400
```

I run the standard julia package from my linux distro
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

**Comment by 00vareladavid** [comment] 2019-11-30 00:59
Closing as a duplicate of #1453, which was recently fixed by #1489.

@PaulXiCao by the way, the Pkg API syntax is different from the REPL syntax. The REPL version of a command such as `Pkg.build("Foo")` is actually `pkg> build Foo`. In that case, the REPL should autocomplete correctly. You can find more help in the [docs](https://julialang.github.io/Pkg.jl/v1/repl/).

**Closed by 00vareladavid** 2019-11-30 00:59 UTC
