### ISSUE TITLE
dev SomePackage should look also for dir "SomePackage.jl"

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/Pkg.jl#1478] opened 2019-10-30 08:08 UTC
It happens that I clone a julia package myself from github in my dev directory, but then the package directory will look like "SomePackage.jl". But when doing `pkg> dev SomePackage`, it will overlook "SomePackage.jl" and clone it again into "SomePackage".

I just had an WTF moment when looking at a file in my editor, loading the package, and see it having a contracitory behavior compared to the files. I started to seriously question my Julia skills :sweat_smile:  but fortunately I discovered the mischief quite fast and didn't loose much time.

The change is quite simple, but after 5 minutes I didn't find a worflow to try out my changes locally with `Pkg`. But if no-one beats me to it, I guess I will make a PR eventually.

**Comment by fredrikekre** [comment] 2019-10-30 09:30
Duplicate of #837

**Closed by fredrikekre** 2019-10-30 09:30 UTC
