### ISSUE TITLE
manifest_usage.toml gets corrupted in a distributed environment

### ISSUE THREAD

**Issue by ghost** [JuliaLang/Pkg.jl#684] opened 2018-08-23 03:55 UTC
When launching multiple julia processes `manifest_usage.toml` gets corrupted by concurrent writes that leads to `gc` having trouble:

```
pkg> gc
ERROR: Pkg.TOML.ParserError(594, 594, "expected a key but found an empty string")

...and 1 more exception(s).

Stacktrace:
 [1] parse(::Base.GenericIOBuffer{Array{UInt8,1}}) at /home/src/julia.7/usr/share/julia/stdlib/v1.0/Pkg/ext/TOML/src/TO
ML.jl:33                                                                                                              
 [2] parse at /home/src/julia.7/usr/share/julia/stdlib/v1.0/Pkg/ext/TOML/src/TOML.jl:40 [inlined]
 [3] #gc#45(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context) at
 /home/src/julia.7/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:292                                                     
 [4] gc at /home/src/julia.7/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:273 [inlined]
```

removing the file clears the issue.

**Comment by StefanKarpinski** [comment] 2018-08-23 04:08
Definitely an issue. We should do some file locking here. @vtjnash, what's the current best way?

**Comment by vtjnash** [comment] 2018-08-23 06:40
Use atomic file operations. (Never modify or truncate an existing file.)

**Comment by KristofferC** [comment] 2019-07-20 19:12
I think this should be fixed now.

**Comment by timholy** [comment] 2020-03-20 11:30
This just happened to me.
```julia
(@v1.5) pkg> gc
ERROR: Pkg.TOML.ParserError(2128571, 2128572, "expected `=`, but found `:`")
Stacktrace:
 [1] parse(::Base.GenericIOBuffer{Array{UInt8,1}}) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/ext/TOML/src/TOML.jl:37
 [2] parse at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/ext/TOML/src/TOML.jl:44 [inlined]
 [3] (::Pkg.API.var"#collect_usage!#83")(::Dict{String,Dates.DateTime}, ::String) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:353
 [4] gc(::Pkg.Types.Context; collect_delay::Dates.Day, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:376
 [5] gc at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:330 [inlined] (repeats 2 times)
 [6] do_cmd!(::Pkg.REPLMode.Command, ::REPL.LineEditREPL) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:400
 [7] do_cmd(::REPL.LineEditREPL, ::String; do_rethrow::Bool) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:381
 [8] do_cmd at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:376 [inlined]
 [9] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:542
 [10] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [11] invokelatest at ./essentials.jl:709 [inlined]
 [12] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:2354
 [13] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:1088
 [14] run_repl(::REPL.AbstractREPL, ::Any) at /home/tim/src/julia-master/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:238
 [15] (::Base.var"#790#792"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
 [16] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [17] invokelatest at ./essentials.jl:709 [inlined]
 [18] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
 [19] exec_options(::Base.JLOptions) at ./client.jl:305
 [20] _start() at ./client.jl:490
```

**Comment by timholy** [comment] 2020-03-20 11:32
My `manifest_usage.toml` isn't even 2128571 characters long:
```sh
tim@diva:~/.julia/logs$ wc -m manifest_usage.toml 
539860 manifest_usage.toml
```

**Comment by StefanKarpinski** [comment] 2020-03-20 12:41
I'm not sure if length matters here. The issue is that we append to the file and if two processes append at the same time, the file can end up being corrupted. It would be interesting to see how it ended up corrupt to see if that theory is correct. Short of making Pidfiles a stdlib, I'm not sure how to fix this. We could rewrite the entire file via a tempfile on each usage, but that feels like it might be too slow.

**Comment by timholy** [comment] 2020-03-20 13:16
> I'm not sure if length matters here. 

I just meant that the `ParserError` indicated a position that isn't in the file, assuming that's the file it's reading.

**Comment by StefanKarpinski** [comment] 2020-03-20 13:40
Oh, I see. That is very strange. Can you post the file content as a gist maybe or email it to me?

**Closed** 2022-03-10 02:46 UTC
Labels: help wanted
