### ISSUE TITLE
Artifact install error should be more detailed

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/Pkg.jl#2957] opened 2022-01-25 21:13 UTC
Github seems to be having an issue serving artifacts currently, which has made a few systems I use that have `JULIA_PKG_SERVER=""` set hit this unhelpful error, which even gives the impression it's a local file issue.
i.e. "install" rather than "download", and giving a local file path (I get what it's saying, but it's unclear)

On 1.6.5

```
(@v1.6) pkg> add libsodium_jll
  Installing known registries into `/tmp/1233214`
       Added registry `General` to `/tmp/1233214/registries/General`
   Resolving package versions...
   Installed libsodium_jll ─ v1.0.20+0
   Installed Preferences ─── v1.2.3
   Installed JLLWrappers ─── v1.4.0
  Downloaded artifact: libsodium
    Updating `/tmp/1233214/environments/v1.6/Project.toml`
  [a9144af2] + libsodium_jll v1.0.20+0
    Updating `/tmp/1233214/environments/v1.6/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.4.0
  [21216c6a] + Preferences v1.2.3
  [a9144af2] + libsodium_jll v1.0.20+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
   Installed libvorbis_jll ───────────── v1.3.7+1
   Installed MappedArrays ────────────── v0.4.1
   Installed Xorg_libXdmcp_jll ───────── v1.1.3+4
   Installed libpng_jll ──────────────── v1.6.38+0
   Installed PaddedViews ─────────────── v0.5.11
   Installed Compat ──────────────────── v3.41.0
   Installed Xorg_libpthread_stubs_jll ─ v0.1.0+3
   Installed MosaicViews ─────────────── v0.3.3
   Installed Xorg_libXau_jll ─────────── v1.0.9+4
   Installed FreeType2_jll ───────────── v2.10.4+0
   Installed Graphics ────────────────── v1.1.1
   Installed ColorTypes ──────────────── v0.11.0
   Installed OpenSSL_jll ─────────────── v1.1.13+0
   Installed Libgpg_error_jll ────────── v1.42.0+0
   Installed OpenSpecFun_jll ─────────── v0.5.5+0
   Installed FileIO ──────────────────── v1.12.0
   Installed FFMPEG ──────────────────── v0.4.1
   Installed Colors ──────────────────── v0.12.8
   Installed XML2_jll ────────────────── v2.9.12+0
   Installed Xorg_libX11_jll ─────────── v1.6.9+4
   Installed Libgcrypt_jll ───────────── v1.8.7+0
   Installed libass_jll ──────────────── v0.15.1+0
   Installed TensorCore ──────────────── v0.1.1
   Installed x265_jll ────────────────── v3.5.0+0
   Installed FriBidi_jll ─────────────── v1.0.10+0
   Installed XSLT_jll ────────────────── v1.1.34+0
   Installed Expat_jll ───────────────── v2.2.10+0
   Installed FixedPointNumbers ───────── v0.8.4
   Installed Requires ────────────────── v1.3.0
   Installed Pixman_jll ──────────────── v0.40.1+0
   Installed Libiconv_jll ────────────── v1.16.1+1
   Installed Xorg_libXrender_jll ─────── v0.9.10+4
   Installed ColorVectorSpace ────────── v0.9.8
   Installed AbstractFFTs ────────────── v1.1.0
   Installed Reexport ────────────────── v1.2.2
  Downloaded artifact: x264
  Downloaded artifact: HarfBuzz
  Downloaded artifact: LZO
  Downloaded artifact: Cairo
  Downloaded artifact: LAME
ERROR: Unable to automatically install 'LAME' from '/tmp/1233214/packages/LAME_jll/fcCkK/Artifacts.toml'
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:445
  [3] ensure_all_artifacts_installed(artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Artifacts.jl:510
  [4] download_artifacts(ctx::Pkg.Types.Context, pkg_roots::Vector{String}; platform::Base.BinaryPlatforms.Platform, verbose::Bool, io::Base.TTY)
    @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:710
  [5] download_artifacts(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; platform::Base.BinaryPlatforms.Platform, julia_version::VersionNumber, verbose::Bool, io::Base.TTY)
    @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:687
  [6] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Vector{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1242
  [7] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:204
  [8] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:80
  [9] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:78
 [10] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:408
 [11] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:386
 [12] do_cmd
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:377 [inlined]
 [13] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:550
 [14] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [15] invokelatest
    @ ./essentials.jl:706 [inlined]
 [16] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
 [17] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1126
 [18] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:411

```

**Comment by DilumAluthge** [comment] 2022-01-25 21:18
https://github.com/giordano/DebugArtifacts.jl might be useful for debugging.

**Comment by giordano** [comment] 2022-01-27 18:53
Basically a duplicate of #1659.

> giordano/DebugArtifacts.jl might be useful for debugging

Yes, although it'd be nicer to not hide these errors here

**Comment by DilumAluthge** [comment] 2022-01-27 19:26
To me, it would make sense to always show those errors. Is there a compelling reason to hide them?

**Comment by IanButterworth** [comment] 2022-01-27 19:27
Yeah, the tricky part is that the pkgserver is tried first for all artifacts, even if it doesn't serve that artifact, so you cant error immediately. 

I'm thinking if nothing succeeds it should print a summary of each error for each link tried.

That might make people ask why the pkgserver is 404-ing as well as GitHub failing, for instance, I think that's more explainable than the current error.

**Comment by DilumAluthge** [comment] 2022-01-27 19:28
Maybe we write all the errors to an `up = IOBuffer()`, but we don't actually print them if the artifact download succeeds? But if the artifact download fails, then we immediately dump `read(io, String)`?

**Comment by giordano** [comment] 2022-01-27 19:29
> I'm thinking if nothing succeeds it should print a summary of each error for each link tried.

Yes, of course can't error put immediately, but if nothing works it'd be good to know why

**Closed** 2022-02-02 21:33 UTC
