### ISSUE TITLE
strange interaction between SpecialFunctions and Distributions

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/Pkg.jl#1403] opened 2019-09-19 18:56 UTC
I think this may be a Pkg problem: https://github.com/JuliaMath/SpecialFunctions.jl/issues/182#issuecomment-533263033

**Comment by fredrikekre** [comment] 2019-09-19 19:56
Duplicate of #110, fixed by #1330

**Closed by fredrikekre** 2019-09-19 19:56 UTC
