### ISSUE TITLE
Precompiling REPLExt, cache misses every time. mismatched flags (2), dep uuid changed (4)

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/Pkg.jl#3788] opened 2024-02-10 23:32 UTC
I'm seeing REPLExt precompilation every single time I try to use Pkg or enter the Pkg REPL.

```
[ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: mismatched flags (2), dep uuid changed (4)
```

```julia
$ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1550 (2024-02-10)
 _/ |\__'_|_|_|\__'_|  |  Commit 604609a3fc* (0 days old master)
|__/                   |

julia> using Pkg
[ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: mismatched flags (2), dep uuid changed (4))

julia> exit()

$ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1550 (2024-02-10)
 _/ |\__'_|_|_|\__'_|  |  Commit 604609a3fc* (0 days old master)
|__/                   |

julia> [ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: mismatched flags (2), dep uuid changed (4))

julia> exit()

$ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1550 (2024-02-10)
 _/ |\__'_|_|_|\__'_|  |  Commit 604609a3fc* (0 days old master)
|__/                   |

julia> [ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: mismatched flags (2), dep uuid changed (4))
julia> exit()

$ ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1550 (2024-02-10)
 _/ |\__'_|_|_|\__'_|  |  Commit 604609a3fc* (0 days old master)
|__/                   |

julia> using Pkg
[ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: mismatched flags (2), dep uuid changed (4))
```

**Comment by mkitti** [comment] 2024-02-10 23:41
I got the following when running with `JULIA_DEBUG=loading`. It might be to problems with compilation. I will try cleaning and rebuilding.

```
┌ Debug: Loading object cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/Serialization/zGad9_z9MXU.so for Serialization [9e88b42a-f829-5b0c-bbe9-9e923198166b]
└ @ Base loading.jl:1127
┌ Debug: Loading object cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/Pkg/tUTdb_z9MXU.so for Pkg [44cfe95a-1eb2-52ea-b672-e2afdf69b78f]
└ @ Base loading.jl:1127
┌ Debug: Rejecting cache file /home/mkitti/.julia/compiled/v1.11/REPLExt/m7ggP_iP0Qa.ji because uuid mapping for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => Base.PkgId(Base.UUID("d6f4376e-aef5-505a-96c1-9c027394607a"), "Markdown") has changed, expected Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => nothing
└ @ Base loading.jl:3461
┌ Debug: Rejecting cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/REPLExt/m7ggP_z9MXU.ji because uuid mapping for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => Base.PkgId(Base.UUID("d6f4376e-aef5-505a-96c1-9c027394607a"), "Markdown") has changed, expected Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => nothing
└ @ Base loading.jl:3461
┌ Debug: Rejecting cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/REPLExt/m7ggP_gbs0d.ji for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:3351
┌ Debug: Rejecting cache file /home/mkitti/.julia/compiled/v1.11/REPLExt/m7ggP_iP0Qa.ji because uuid mapping for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => Base.PkgId(Base.UUID("d6f4376e-aef5-505a-96c1-9c027394607a"), "Markdown") has changed, expected Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => nothing
└ @ Base loading.jl:3461
┌ Debug: Rejecting cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/REPLExt/m7ggP_z9MXU.ji because uuid mapping for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => Base.PkgId(Base.UUID("d6f4376e-aef5-505a-96c1-9c027394607a"), "Markdown") has changed, expected Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => nothing
└ @ Base loading.jl:3461
┌ Debug: Rejecting cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/REPLExt/m7ggP_gbs0d.ji for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:3351
┌ Debug: Rejecting cache file /home/mkitti/.julia/compiled/v1.11/REPLExt/m7ggP_iP0Qa.ji because uuid mapping for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => Base.PkgId(Base.UUID("d6f4376e-aef5-505a-96c1-9c027394607a"), "Markdown") has changed, expected Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => nothing
└ @ Base loading.jl:3461
┌ Debug: Rejecting cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/REPLExt/m7ggP_z9MXU.ji because uuid mapping for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => Base.PkgId(Base.UUID("d6f4376e-aef5-505a-96c1-9c027394607a"), "Markdown") has changed, expected Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") => nothing
└ @ Base loading.jl:3461
┌ Debug: Rejecting cache file /home/mkitti/src/julia/usr/share/julia/compiled/v1.11/REPLExt/m7ggP_gbs0d.ji for Base.PkgId(Base.UUID("e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b"), "REPLExt") since the flags are mismatched
│   current session: use_pkgimages = true, debug_level = 1, check_bounds = 0, inline = true, opt_level = 2
│   cache file:      use_pkgimages = true, debug_level = 1, check_bounds = 1, inline = true, opt_level = 2
└ @ Base loading.jl:3351
[ Info: Precompiling REPLExt [e5eb5ef1-03cf-53a7-ae1d-5a66b08e832b] (cache misses: mismatched flags (2), dep uuid changed (4))
```

**Comment by IanButterworth** [comment] 2024-02-11 01:02
Duplicate of https://github.com/JuliaLang/julia/issues/53264

**Closed** 2024-02-11 01:03 UTC
