### ISSUE TITLE
Suggestions for typos

### ISSUE THREAD

**Issue by jtrakk** [JuliaLang/Pkg.jl#2962] opened 2022-01-28 21:52 UTC
```jl
 pkg> add Macrotools
ERROR: The following package names could not be resolved:
 * Macrotools (not found in project, manifest or registry)
```
Could it suggest

```jl
 pkg> add Macrotools
ERROR: The following package names could not be resolved:
 * Macrotools (not found in project, manifest or registry)
Did you mean: add MacroTools? [y/n]
```

**Comment by tbeason** [comment] 2022-02-09 13:07
Duplicate of #2911 ?

**Closed** 2022-02-09 13:12 UTC
