### ISSUE TITLE
Typo at the Pkg REPL prompt brings down the process

### ISSUE THREAD

**Issue by Keno** [JuliaLang/Pkg.jl#3786] opened 2024-02-10 19:52 UTC
```
 ~/julia//julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.1547 (2024-02-10)
 _/ |\__'_|_|_|\__'_|  |  Commit a59f2192ac (0 days old master)
|__/                   |

(DAECompiler) pkg> test'
Unhandled Task ERROR: Pkg.Types.PkgError("unterminated quote")
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/Types.jl:68
  [2] lex(cmd::String)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:218
  [3] tokenize(cmd::String)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:226
  [4] parse
    @ ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:282 [inlined]
  [5] prepare_cmd
    @ ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:378 [inlined]
  [6] do_cmds
    @ ~/julia/usr/share/julia/stdlib/v1.11/Pkg/ext/REPLExt/REPLExt.jl:87 [inlined]
  [7] (::REPLExt.var"#31#34"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ REPLExt ~/julia/usr/share/julia/stdlib/v1.11/Pkg/ext/REPLExt/REPLExt.jl:121
  [8] #invokelatest#2
    @ ./essentials.jl:1025 [inlined]
  [9] invokelatest
    @ ./essentials.jl:1022 [inlined]
 [10] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2734
 [11] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1410
 [12] (::REPL.var"#75#81"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:458
ERROR: TaskFailedException
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:944
  [2] wait()
    @ Base ./task.jl:1008
  [3] wait(c::Base.GenericCondition{ReentrantLock}; first::Bool)
    @ Base ./condition.jl:130
  [4] wait
    @ ./condition.jl:125 [inlined]
  [5] take_buffered(c::Channel{Any})
    @ Base ./channels.jl:493
  [6] take!
    @ ./channels.jl:487 [inlined]
  [7] repl_backend_loop(backend::REPL.REPLBackend, get_module::Function)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:315
  [8] start_repl_backend(backend::REPL.REPLBackend, consumer::Any; get_module::Function)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:305
  [9] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool, backend::Any)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:461
 [10] run_repl(repl::REPL.AbstractREPL, consumer::Any)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:447
 [11] (::Base.var"#1119#1121"{Bool, Symbol, Bool})(REPL::Module)
    @ Base ./client.jl:440
 [12] #invokelatest#2
    @ ./essentials.jl:1025 [inlined]
 [13] invokelatest
    @ ./essentials.jl:1022 [inlined]
 [14] run_main_repl(interactive::Bool, quiet::Bool, banner::Symbol, history_file::Bool, color_set::Bool)
    @ Base ./client.jl:424
 [15] repl_main
    @ ./client.jl:561 [inlined]
 [16] _start()
    @ Base ./client.jl:535

    nested task error: unterminated quote
    Stacktrace:
      [1] pkgerror(msg::String)
        @ Pkg.Types ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/Types.jl:68
      [2] lex(cmd::String)
        @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:218
      [3] tokenize(cmd::String)
        @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:226
      [4] parse
        @ ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:282 [inlined]
      [5] prepare_cmd
        @ ~/julia/usr/share/julia/stdlib/v1.11/Pkg/src/REPLMode/REPLMode.jl:378 [inlined]
      [6] do_cmds
        @ ~/julia/usr/share/julia/stdlib/v1.11/Pkg/ext/REPLExt/REPLExt.jl:87 [inlined]
      [7] (::REPLExt.var"#31#34"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
        @ REPLExt ~/julia/usr/share/julia/stdlib/v1.11/Pkg/ext/REPLExt/REPLExt.jl:121
      [8] #invokelatest#2
        @ ./essentials.jl:1025 [inlined]
      [9] invokelatest
        @ ./essentials.jl:1022 [inlined]
     [10] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
        @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2734
     [11] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
        @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1410
     [12] (::REPL.var"#75#81"{REPL.LineEditREPL, REPL.REPLBackendRef})()
        @ REPL ~/julia/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:458
```

**Comment by vtjnash** [comment] 2024-02-10 20:02
Duplicate of https://github.com/JuliaLang/Pkg.jl/issues/3787

**Closed by vtjnash** 2024-02-10 20:02 UTC
