### ISSUE TITLE
MethodError during update

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/Pkg.jl#2059] opened 2020-10-01 02:55 UTC
I saw this error when running `update`. It went away after building and restarting, but I'll report it here in case it brings anything useful to mind:

```
Updating `~/.julia/environments/v1.6/Project.toml`
  [537997a7] ↑ AbstractPlotting v0.12.10 ⇒ v0.12.12
  [c3b6d118] ↑ BitIntegers v0.2.3 ⇒ v0.2.4
  [713c75ef] ↑ Franklin v0.10.0 ⇒ v0.10.3
  [b4f0291d] ↑ LazySets v1.37.9 ⇒ v1.37.10
  [961ee093] ↑ ModelingToolkit v3.20.0 ⇒ v3.20.1
  [6fe1bfb0] ↑ OffsetArrays v1.2.1 ⇒ v1.3.0
  [91a5bcdd] ↑ Plots v1.6.6 ⇒ v1.6.7
  [a4e569a6] ERROR: MethodError: no method matching isless(::VersionNumber, ::Pkg.Types.VersionSpec)
Closest candidates are:
  isless(::Missing, ::Any) at missing.jl:87
  isless(::Any, ::Missing) at missing.jl:88
  isless(::VersionNumber, ::VersionNumber) at version.jl:180
Stacktrace:
  [1] <(x::VersionNumber, y::Pkg.Types.VersionSpec)
    @ Base ./operators.jl:279
  [2] >(x::Pkg.Types.VersionSpec, y::VersionNumber)
    @ Base ./operators.jl:305
  [3] print_diff(ctx::Pkg.Types.Context, old::Pkg.Types.PackageSpec, new::Pkg.Types.PackageSpec)
    @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1673
  [4] print_status(ctx::Pkg.Types.Context, old_ctx::Pkg.Types.Context, header::Symbol, uuids::Vector{Base.UUID}, names::Vector{String}; manifest::Bool, diff::Bool)
    @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1744
  [5] status(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; header::Symbol, mode::Pkg.Types.PackageMode, git_diff::Bool, env_diff::Pkg.Types.EnvCache)
    @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1807
  [6] show_update
    @ ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1774 [inlined]
  [7] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, level::Pkg.Types.UpgradeLevel)
    @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1257
  [8] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; level::Pkg.Types.UpgradeLevel, mode::Pkg.Types.PackageMode, update_registry::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:249
  [9] up
    @ ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:225 [inlined]
 [10] #up#38
    @ ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:68 [inlined]
 [11] up(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:68
 [12] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:403
 [13] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:381
 [14] do_cmd
    @ ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:376 [inlined]
 [15] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode ~/src/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:545
 [16] #invokelatest#2
    @ ./essentials.jl:709 [inlined]
 [17] invokelatest
    @ ./essentials.jl:708 [inlined]
 [18] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2435
 [19] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1124
 [20] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:395
```

**Comment by DilumAluthge** [comment] 2020-10-01 04:53
Duplicate of https://github.com/JuliaLang/Pkg.jl/issues/2051?

**Closed** 2020-10-02 09:46 UTC
