### ISSUE TITLE
`purge` method?

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/Pkg.jl#1459] opened 2019-10-21 02:38 UTC
Installing new versions of dev packages can at times turn into a nightmare of removing old versions from clones, dev folder and the registry, when for whatever reason an old clone blocks adding the new verison of the package.

It would be good if there was a `purge` command that got rid of all traces of a package from the registry, clones and dev folders etc.

**Comment by DilumAluthge** [comment] 2019-10-21 03:17
Why not just `rm -rf ~/.julia`?

**Comment by rafaqz** [comment] 2019-10-21 03:40
I mean purge for a single package. Deleting all of .julia means setting up everything again, not just one package. Which might mean running `dev` for 20 git repos...

Maybe not all your changes in dev are committed, maybe you have multiple projects going at once, maybe you are in the middle of working on something and one package is refusing to update and you are pulling your hair out...

To avoid starting from scratch completely we normally delete the `clones` folder, run `] rm BrokenPackage` and deleting the packages folder in `/dev`. Then try again. But you tend to forget this sequence, and it seems dirty.

**Comment by DilumAluthge** [comment] 2019-10-21 03:50
Ahhh I see what you mean

**Comment by rafaqz** [comment] 2019-10-21 03:54
Yeah. I'm not sure what actually blocks `dev` updating package code. It could be rebases in the git history. That would also be good to resolve, but `purge` would be a workaround for this and all the other reasons things will break.

**Comment by DilumAluthge** [comment] 2019-10-21 03:58
If you have a packaged `dev`-ed, Pkg will never even attempt to update it. That’s not a bug, that’s the intended design.

**Comment by rafaqz** [comment] 2019-10-21 04:25
That behaviour is fine.

But if the package has been deleted with `rm`, `dev SomePackage` probably should update it, or at least warn if it hasn't. 

But the worst is that you can even delete the package from `dev` and on some occasions `dev SomePackage` will still get the old version from clones, and still not update it, or even tell you it has done that!

**Comment by KristofferC** [comment] 2019-10-21 07:43
There is a cache of repositories in `.julia/clones´. The ones that end with `_full` are the ones used for `dev`. These should be updated on `dev` but are not right now. The update should be put approximately at

https://github.com/JuliaLang/Pkg.jl/blob/master/src/Types.jl#L509

There is code that updates the registry all ready so someone could probably adapt that code.

**Comment by fredrikekre** [comment] 2019-10-21 15:05
Duplicate of #465

**Closed by fredrikekre** 2019-10-21 15:05 UTC

**Comment by adigitoleo** [comment] 2021-06-07 09:29
Not convinced about the duplicate flag. This one seems to be more general:

> It would be good if there was a purge command that got rid of all traces of a package from the registry, clones and dev folders etc

At the moment, I am trying to debug my julia environment and came here searching for that kind of thing. I don't know the ins and outs of the Pkg yet, but I can tell that `rm <package>` is leaving stuff behind and I want to start from scratch with a problematic package. I've only found this and [a stackoverflow answer](https://stackoverflow.com/a/50835974) (and comment) so far, let me know if I missed some other resource.
