### ISSUE TITLE
`Pkg.add` throws a `BoundsError` when installing packages using `PackageSpec(url=xxx)`

### ISSUE THREAD

**Issue by asparagii** [JuliaLang/Pkg.jl#2937] opened 2022-01-11 14:50 UTC
This happens on a fresh install of julia on Arch Linux.
```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |


julia> using Pkg

julia> Pkg.add(PackageSpec(url="https://github.com/JuliaLang/Example.jl.git"))
     Cloning git-repo `https://github.com/JuliaLang/Example.jl.git`
ERROR: BoundsError: attempt to access 1024-element Vector{UInt8} at index [0x0000000000000001:0x00005609ad033420]
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908* (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, skylake)
```

This happens whenever I try to install an unregistered package (via URL). Registered packages install fine.
The pkg repl has the same behaviour (though the stacktrace is of course slightly different, the error is the same).

**Comment by fredrikekre** [comment] 2022-01-11 16:13
Duplicate of #2779

**Closed by fredrikekre** 2022-01-11 16:13 UTC

**Comment by asparagii** [comment] 2022-01-11 16:18
#2779 seems to be about packages from private registries - which i guess means repositories that are not public.
This issue right here is talking more generally about unregistered packages.
Is my guess correct?

**Comment by fredrikekre** [comment] 2022-01-11 16:19
It is related to SSH keys when git cloning I believe, no matter if it is public or not.

**Comment by asparagii** [comment] 2022-01-11 16:23
I am using (in theory) https and not SSH, as you can see from the example.
Though it might be the case that git is replacing https with SSH under the hood. I'll check.

**Comment by fredrikekre** [comment] 2022-01-11 16:25
Do you not have a longer stacktrace as in the other issue?

**Comment by asparagii** [comment] 2022-01-11 16:30
> Do you not have a longer stacktrace as in the other issue?
No, I don't.

But it's not important, since the issue was in my git configuration.

This rule replaces every https url with ssh.
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```
I am using this because it's (kinda) needed to download private repositories in Golang - completely unrelated.

Anyway, by removing the rule the error doesn't appear anymore, which means that this issue was indeed a duplicate of #2779.

Thanks and sorry for the trouble.

**Comment by fredrikekre** [comment] 2022-01-11 16:33
If you are using Julia 1.7 you can try with setting the environment variable `JULIA_PKG_USE_CLI_GIT=true` to use `git` instead of `libgit2`, does that fix it?

**Comment by asparagii** [comment] 2022-01-11 16:38
Yes, it does!

```
[michele@dell ~]$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> using Pkg

julia> Pkg.add(PackageSpec(url="https://github.com/JuliaLang/Example.jl.git"))
    Updating git-repo `https://github.com/JuliaLang/Example.jl.git`
ERROR: BoundsError: attempt to access 1024-element Vector{UInt8} at index [0x0000000000000001:0x000055f06916ebf0]
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

julia> exit()
[michele@dell ~]$ JULIA_PKG_USE_CLI_GIT=true julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> using Pkg

julia> Pkg.add(PackageSpec(url="https://github.com/JuliaLang/Example.jl.git"))
    Updating git-repo `https://github.com/JuliaLang/Example.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [7876af07] + Example v0.5.4 `https://github.com/JuliaLang/Example.jl.git#master`
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [7876af07] + Example v0.5.4 `https://github.com/JuliaLang/Example.jl.git#master`

julia> exit()
```
