### ISSUE TITLE
ArgumentError   compiled ji exists use force=true to remove

### ISSUE THREAD

**Issue by musm** [JuliaLang/Pkg.jl#1920] opened 2020-07-10 02:47 UTC
This is on a recent master build of julia.

I keep running into errors like the following. 
```julia
julia> using Crayons
[ Info: Precompiling Crayons [a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f]
ERROR: ArgumentError: 'C:\Users\Mus\.julia\compiled\v1.6\Crayons\TXPcU_RsVR4.ji' exists. `force=true` is required to remove 'C:\Users\Mus\.julia\compiled\v1.6\Crayons\TXPcU_RsVR4.ji' before copying.
Stacktrace:
 [1] checkfor_mv_cp_cptree(src::String, dst::String, txt::String; force::Bool)
   @ Base.Filesystem .\file.jl:308
 [2] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
   @ Base.Filesystem .\file.jl:345
 [3] rename(src::String, dst::String)
   @ Base.Filesystem .\file.jl:898
 [4] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1341
 [5] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1030
 [6] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:928
 [7] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923
 
```

This has required me to manually remove these files and try precompilation again. I'm not sure if there's an easier way to fix this. I'm not exactly sure how I'm supposed to use `force=true` in the context of the error message.

**Comment by DilumAluthge** [comment] 2020-07-10 03:01
If you close Julia, rename your `.julia` directory to something else, and then start Julia and do `] add Crayons` and `using Crayons`, are you able to reproduce the error?

Also, does this only happen on Windows?

**Comment by musm** [comment] 2020-07-10 03:09
> If you close Julia, rename your .julia directory to something else, and then start Julia and do ] add Crayons and using Crayons, are you able to reproduce the error?

If you forcibly removed the precompiled files, it will of course work. The  issue crops up from time to time, when then restarting julia and attempting to do something like `use Crayons` again (the package doesn't matter, as I've had the same errors when attempting to use `Images`). I have no idea how to reproducibly generate this error. But I've ran into this same error more then several times in the last day.

**Comment by DilumAluthge** [comment] 2020-07-10 03:26
I think this issue needs to be moved to the main Julia repo, as it looks like a bug in Base.

The function in question is here: https://github.com/JuliaLang/julia/blob/80a016751545b323e81ae18bb9ced70afd8902fa/base/loading.jl#L1301

The error is occurring in the call to `rename` here: https://github.com/JuliaLang/julia/blob/80a016751545b323e81ae18bb9ced70afd8902fa/base/loading.jl#L1341

This is puzzling to me. The destination file should never actually exist, since it should have been deleted in this step: https://github.com/JuliaLang/julia/blob/80a016751545b323e81ae18bb9ced70afd8902fa/base/loading.jl#L1311

**Comment by DilumAluthge** [comment] 2020-07-10 03:27
When you experience this bug, are you running multiple Julia sessions at the same time? Is there any chance that two different Julia processes are trying to write to the same precompilation directory at the same time?

**Comment by musm** [comment] 2020-07-10 03:34
> When you experience this bug, are you running multiple Julia sessions at the same time? Is there any chance that two different Julia processes are trying to write to the same precompilation directory at the same time?

No. 

I believe it  seems to occur when something triggers a recompilation of my packages. Is there a reproducible way to that triggers such a case?

**Comment by DilumAluthge** [comment] 2020-07-10 03:37
> > When you experience this bug, are you running multiple Julia sessions at the same time? Is there any chance that two different Julia processes are trying to write to the same precompilation directory at the same time?
> 
> No.
> 
> I believe it seems to occur when something triggers a recompilation of my packages. Is there a reproducible way to that triggers such a case?

It's certainly going to be tricky to reproduce this...

I suppose you could `dev` some packages, `import them (thus trigger precompilation), and then close Julia, make some edits to those packages, then reopen Julia and `import` the packages. In theory that should trigger re-precompilation.

**Comment by fredrikekre** [comment] 2020-07-11 23:32
Closing in favor of https://github.com/JuliaLang/julia/issues/36621

**Closed by fredrikekre** 2020-07-11 23:32 UTC
