### ISSUE TITLE
can't download registry form pkgserver made by myself on windows

### ISSUE THREAD

**Issue by shihaoyan2018** [JuliaLang/Pkg.jl#1660] opened 2020-02-05 16:59 UTC
it can download registry from `pkg.julialang.org` and `kr.pkg.juliang.org` ,but it can't download registry form pkgserver made by myself .

warning message:

`┌ Warning: could not download http://45.77.28.188:8000/registries`
`└ @ Pkg.Types D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:880`

versioninfo():

`Julia Version 1.5.0-DEV.233`
`Commit aa36eefa17 (2020-02-05 08:25 UTC)`
`Platform Info:`
`  OS: Windows (x86_64-w64-mingw32)`
`  CPU: AMD Ryzen 3 3200G with Radeon Vega Graphics`
  `WORD_SIZE: 64`
  `LIBM: libopenlibm`
 `LLVM: libLLVM-9.0.1 (ORCJIT, znver1)`

and i am sure of my pkg server can be used,because i try it on my linux laptop and it work.
my pkg server listen `0.0.0.0:8000` 

`(base) root@vultr:~/.julia/packages/PkgServer/RW5FL/bin# /root/test/julia-1.4.0-rc1/bin/julia --project run_server.jl`
`┌ Info: downloading resource`
`│   server = "https://pkg.julialang.org"`
`└   resource = "/registry/23338594-aafe-5451-b93e-139f81909106/8f554d186439f91be8500dd41d8c2f8fbdfcb5f6"`
`┌ Info: new current registry hash`
`│   uuid = "23338594-aafe-5451-b93e-139f81909106"`
`│   hash = "8f554d186439f91be8500dd41d8c2f8fbdfcb5f6"`
`│   servers =`
`│    1-element Array{String,1}:`
`└     "https://pkg.julialang.org"`
`[ Info: server listening on 0.0.0.0:8000`

**Comment by fredrikekre** [comment] 2020-02-05 18:50
What is `45.77.28.188`? Maybe you can try to set `JULIA_PKG_SERVER=localhost:8000` instead?

**Comment by shihaoyan2018** [comment] 2020-02-06 05:37
> What is `45.77.28.188`? If that is your external internet IP adress you might have to open up port 8000. Maybe you can try to set `JULIA_PKG_SERVER=localhost:8000` instead?

It is a VPS which I buy it on Vultr. So the pkg server and julia client are not in a same location. And I'm  sure of that the port 8000 is open.Because using `HTTP.get("http://45.77.28.188:8000/registries")`  is normal.
`julia> HTTP.get("http://45.77.28.188:8000/registries")`
`HTTP.Messages.Response:`
`"""`
`HTTP/1.1 200 OK`
`Content-Length: 88`
`Content-Encoding: gzip`
`/registry/23338594-aafe-5451-b93e-139f81909106/1f34a616de78aa14be43a305a1b6059bf3589c2c`
`"""`

**Comment by fredrikekre** [comment] 2020-02-06 06:38
Ah, you are on Windows, probably a duplicate of #1642 then.

**Closed by fredrikekre** 2020-02-06 06:38 UTC
