### ISSUE TITLE
Unable to add unregistered package that depends on other unregistered packages

### ISSUE THREAD

**Issue by krrutkow** [JuliaLang/Pkg.jl#698] opened 2018-08-24 18:53 UTC
I have two unregistered packages where `Package2` depends on `Package1`.  In Package2, the project file has `Package1 = "e0067cb0-..."` and the manifest has `repo-url = "file:///tmp/Package1.jl.git"` in it, but when adding `Package2` to the default environment, the dependency is not automatically installed.
```
(v1.0) pkg> add file:///tmp/Package2.jl.git
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `file:///tmp/Package2.jl.git`
  Updating git-repo `file:///tmp/Package2.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Package1 [e0067cb0]:
 Package1 [e0067cb0] log:
 ├─Package1 [e0067cb0] has no known versions!
 └─restricted to versions * by Package2 [5b0e73ea] — no versions left
   └─Package2 [5b0e73ea] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─Package2 [5b0e73ea] is fixed to version 0.1.0
```

**Comment by DilumAluthge** [comment] 2018-08-26 20:58
Possible duplicate of JuliaLang/Pkg.jl#492 ?

**Comment by 00vareladavid** [comment] 2019-02-01 03:11
Closing as a duplicate of #1005

**Closed by 00vareladavid** 2019-02-01 03:11 UTC
