### ISSUE TITLE
Pkg add precompiles too many packages, not just dependencies

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/Pkg.jl#3230] opened 2022-10-19 12:02 UTC
```
(@v1.8) pkg> add URIs
   Resolving package versions...
    Updating `~/.julia/environments/v1.8/Project.toml`
  [5c2747f8] + URIs v1.4.0
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
Precompiling project...
  Progress [==============================>          ]  3/4
  ◑ PyBullet

eventually I got:

  2 dependencies successfully precompiled in 64 seconds. 372 already precompiled. 2 skipped during auto due to previous errors.
```

but URIs.jl doesn't have any dependencies (or well one, julia). PyBullet has many but URIs isn't one of them, neither a direct one nor indirect (according to JuliaHub).

Fixing this issue would most likely make many people happy, avoid many OOMs.

That's an MWE, though see the interesting horror story (same cause I think) at https://github.com/JuliaWeb/HTTP.jl/issues/945 in B. (OOM, but likely ALSO a different Pkg bug, why didn't I get latest version?).

It's regular Julia (though not latest, in case this is fixed, or will be, on master (or 1.8.2) would such a fix be backported to 1.8.2/3 and 1.6.x?), though from juliaup:
>Version 1.8.1 (2022-09-06)

julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × Intel(R) Xeon(R) CPU D-1541 @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 1 on 16 virtual cores

**Comment by IanButterworth** [comment] 2022-10-19 12:07
Auto precompilation ensures that the entire env is precompiled each time it calls. If it didn't, you'd hit the slow load time precompilation much more often.

Note the "Precompiling project..." not "Precompiling URIs..."

**Comment by PallHaraldsson** [comment] 2022-10-19 12:59
I realize that, maybe I'm misusing the environment (way too much in it), I still think precompilation could be done lazily (for those other), since you might not use right away, and I often CTRL-C precompilation with no bad effect. It will just be done later.

**Comment by IanButterworth** [comment] 2022-10-19 13:19
It is recommended to use smaller project-targeted envs:
1. You spend less time re-precompiling
2. You're much less likely to see compat conflicts, and resolve them if you hit them
3. It's easier to upgrade julia version because otherwise you need to re-add your default env deps to the new default
4. Your work and environment can be made reproducible via git

And using the default env for dev tooling like Revise, BenchmarkTools, SnoopCompile etc. works well as they'll be available no matter which env you're in.

**Comment by PallHaraldsson** [comment] 2022-10-19 17:03
>You can turn off automatic precompilation if you don't want it.

How? I didn't recall that, only fewer or one forked Julia/precompilation. Anyway that's besides the point, there should be sensible defaults (and OOM is a problem for users, very bad), and doing more isn't good unless for sure a benefit. [I'm ok with precompilation for code actually I asked to be added however, by default]

**Comment by DilumAluthge** [comment] 2022-10-19 17:07
https://pkgdocs.julialang.org/dev/api/#Pkg.precompile

https://discourse.julialang.org/t/how-to-disable-automatic-precompilation-of-packages-in-julia-1-6/57053/2?u=dilumaluthge

**Comment by DilumAluthge** [comment] 2022-10-19 17:10
The default behavior seems to work well for most users, as long as you don't use giant mega-environments.

Closing as wontfix.

**Closed by DilumAluthge** 2022-10-19 17:10 UTC

**Comment by PallHaraldsson** [comment] 2022-10-19 17:19
I can't locate a warning about precompilation in the docs, nor a pointer to JULIA_PKG_PRECOMPILE_AUTO which is only documented in its ENV section.

Most people will never look at (though it is linked from the main docs, not searchable there):
https://pkgdocs.julialang.org/dev/api/#Pkg.precompile

I have/had 47 in my environment, not sure it's "giant mega-environment". I'll take your advice see if it avoids OOM, I just know others experience too (possibly with sensible envs or not, not sure).
